//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenLifeLine_NonBlend.EmsSyndicator {
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlSchemaProviderAttribute("ExportSchema")]
    [System.Xml.Serialization.XmlRootAttribute(IsNullable=false)]
    public partial class DAOException : object, System.Xml.Serialization.IXmlSerializable, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Xml.XmlNode[] nodesField;
        
        private static System.Xml.XmlQualifiedName typeName = new System.Xml.XmlQualifiedName("DAOException", "http://web.syndication.ems.com/");
        
        public System.Xml.XmlNode[] Nodes {
            get {
                return this.nodesField;
            }
            set {
                if ((object.ReferenceEquals(this.nodesField, value) != true)) {
                    this.nodesField = value;
                    this.RaisePropertyChanged("Nodes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        public void ReadXml(System.Xml.XmlReader reader) {
            this.nodesField = System.Runtime.Serialization.XmlSerializableServices.ReadNodes(reader);
        }
        
        public void WriteXml(System.Xml.XmlWriter writer) {
            System.Runtime.Serialization.XmlSerializableServices.WriteNodes(writer, this.Nodes);
        }
        
        public System.Xml.Schema.XmlSchema GetSchema() {
            return null;
        }
        
        public static System.Xml.XmlQualifiedName ExportSchema(System.Xml.Schema.XmlSchemaSet schemas) {
            System.Runtime.Serialization.XmlSerializableServices.AddDefaultSchema(schemas, typeName);
            return typeName;
        }
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://web.syndication.ems.com/", ConfigurationName="EmsSyndicator.EmsSyndicator")]
    public interface EmsSyndicator {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(aIdentifer))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GreenLifeLine_NonBlend.EmsSyndicator.getDomainsResponse getDomains(GreenLifeLine_NonBlend.EmsSyndicator.getDomainsRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(aIdentifer))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GreenLifeLine_NonBlend.EmsSyndicator.loginResponse login(GreenLifeLine_NonBlend.EmsSyndicator.loginRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(GreenLifeLine_NonBlend.EmsSyndicator.DAOException), Action="", Name="DAOException")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(aIdentifer))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GreenLifeLine_NonBlend.EmsSyndicator.getEnvironmentsResponse getEnvironments(GreenLifeLine_NonBlend.EmsSyndicator.getEnvironmentsRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(aIdentifer))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GreenLifeLine_NonBlend.EmsSyndicator.notesResponse notes(GreenLifeLine_NonBlend.EmsSyndicator.notesRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(aIdentifer))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GreenLifeLine_NonBlend.EmsSyndicator.helloWorldResponse helloWorld(GreenLifeLine_NonBlend.EmsSyndicator.helloWorldRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(GreenLifeLine_NonBlend.EmsSyndicator.DAOException), Action="", Name="DAOException")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(aIdentifer))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GreenLifeLine_NonBlend.EmsSyndicator.getDataCapturersResponse getDataCapturers(GreenLifeLine_NonBlend.EmsSyndicator.getDataCapturersRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(GreenLifeLine_NonBlend.EmsSyndicator.DAOException), Action="", Name="DAOException")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(aIdentifer))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GreenLifeLine_NonBlend.EmsSyndicator.getCurrentDataResponse getCurrentData(GreenLifeLine_NonBlend.EmsSyndicator.getCurrentDataRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(aIdentifer))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GreenLifeLine_NonBlend.EmsSyndicator.getDataCaptureDataResponse getDataCaptureData(GreenLifeLine_NonBlend.EmsSyndicator.getDataCaptureDataRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(aIdentifer))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GreenLifeLine_NonBlend.EmsSyndicator.getAllSensorRangesResponse getAllSensorRanges(GreenLifeLine_NonBlend.EmsSyndicator.getAllSensorRangesRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(GreenLifeLine_NonBlend.EmsSyndicator.DAOException), Action="", Name="DAOException")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(aIdentifer))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GreenLifeLine_NonBlend.EmsSyndicator.getCurrentSensorRangesForEnvironmentResponse getCurrentSensorRangesForEnvironment(GreenLifeLine_NonBlend.EmsSyndicator.getCurrentSensorRangesForEnvironmentRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(GreenLifeLine_NonBlend.EmsSyndicator.DAOException), Action="", Name="DAOException")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(aIdentifer))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GreenLifeLine_NonBlend.EmsSyndicator.getCurrentSensorRangesResponse getCurrentSensorRanges(GreenLifeLine_NonBlend.EmsSyndicator.getCurrentSensorRangesRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(aIdentifer))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GreenLifeLine_NonBlend.EmsSyndicator.snapShotsResponse snapShots(GreenLifeLine_NonBlend.EmsSyndicator.snapShotsRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(aIdentifer))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GreenLifeLine_NonBlend.EmsSyndicator.measurementsResponse measurements(GreenLifeLine_NonBlend.EmsSyndicator.measurementsRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(aIdentifer))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GreenLifeLine_NonBlend.EmsSyndicator.camerasResponse cameras(GreenLifeLine_NonBlend.EmsSyndicator.camerasRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(aIdentifer))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GreenLifeLine_NonBlend.EmsSyndicator.noteTakersResponse noteTakers(GreenLifeLine_NonBlend.EmsSyndicator.noteTakersRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(aIdentifer))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GreenLifeLine_NonBlend.EmsSyndicator.sensorChannelsResponse sensorChannels(GreenLifeLine_NonBlend.EmsSyndicator.sensorChannelsRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://web.syndication.ems.com/")]
    public partial class user : aIdentifer {
        
        private string usernameField;
        
        private string currentTokenField;
        
        private string userTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string currentToken {
            get {
                return this.currentTokenField;
            }
            set {
                this.currentTokenField = value;
                this.RaisePropertyChanged("currentToken");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string userType {
            get {
                return this.userTypeField;
            }
            set {
                this.userTypeField = value;
                this.RaisePropertyChanged("userType");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(user))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(aData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(measurement))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(snapshot))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(note))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(aDescription))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(domain))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(environment))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(sensorRange))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(aCaptureData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(noteTaker))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(sensorChannel))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(camera))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://web.syndication.ems.com/")]
    public abstract partial class aIdentifer : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(measurement))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(snapshot))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(note))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://web.syndication.ems.com/")]
    public abstract partial class aData : aIdentifer {
        
        private long mesurementDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long mesurementDate {
            get {
                return this.mesurementDateField;
            }
            set {
                this.mesurementDateField = value;
                this.RaisePropertyChanged("mesurementDate");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://web.syndication.ems.com/")]
    public partial class measurement : aData {
        
        private double measurement1Field;
        
        private long sensor_idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("measurement", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public double measurement1 {
            get {
                return this.measurement1Field;
            }
            set {
                this.measurement1Field = value;
                this.RaisePropertyChanged("measurement1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long sensor_id {
            get {
                return this.sensor_idField;
            }
            set {
                this.sensor_idField = value;
                this.RaisePropertyChanged("sensor_id");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://web.syndication.ems.com/")]
    public partial class snapshot : aData {
        
        private string uriField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string uri {
            get {
                return this.uriField;
            }
            set {
                this.uriField = value;
                this.RaisePropertyChanged("uri");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://web.syndication.ems.com/")]
    public partial class note : aData {
        
        private string messageField;
        
        private user authorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public user author {
            get {
                return this.authorField;
            }
            set {
                this.authorField = value;
                this.RaisePropertyChanged("author");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(domain))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(environment))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(sensorRange))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(aCaptureData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(noteTaker))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(sensorChannel))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(camera))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://web.syndication.ems.com/")]
    public abstract partial class aDescription : aIdentifer {
        
        private string titleField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://web.syndication.ems.com/")]
    public partial class domain : aDescription {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://web.syndication.ems.com/")]
    public partial class environment : aDescription {
        
        private long domainIDField;
        
        private long xField;
        
        private long yField;
        
        private long timestampCreatedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long domainID {
            get {
                return this.domainIDField;
            }
            set {
                this.domainIDField = value;
                this.RaisePropertyChanged("domainID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long x {
            get {
                return this.xField;
            }
            set {
                this.xField = value;
                this.RaisePropertyChanged("x");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long y {
            get {
                return this.yField;
            }
            set {
                this.yField = value;
                this.RaisePropertyChanged("y");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public long timestampCreated {
            get {
                return this.timestampCreatedField;
            }
            set {
                this.timestampCreatedField = value;
                this.RaisePropertyChanged("timestampCreated");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://web.syndication.ems.com/")]
    public partial class sensorRange : aDescription {
        
        private double minThresholdField;
        
        private bool minThresholdFieldSpecified;
        
        private double maxThresholdField;
        
        private bool maxThresholdFieldSpecified;
        
        private long sensorIdField;
        
        private int sensorChannelNumField;
        
        private int priorityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public double minThreshold {
            get {
                return this.minThresholdField;
            }
            set {
                this.minThresholdField = value;
                this.RaisePropertyChanged("minThreshold");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool minThresholdSpecified {
            get {
                return this.minThresholdFieldSpecified;
            }
            set {
                this.minThresholdFieldSpecified = value;
                this.RaisePropertyChanged("minThresholdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double maxThreshold {
            get {
                return this.maxThresholdField;
            }
            set {
                this.maxThresholdField = value;
                this.RaisePropertyChanged("maxThreshold");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maxThresholdSpecified {
            get {
                return this.maxThresholdFieldSpecified;
            }
            set {
                this.maxThresholdFieldSpecified = value;
                this.RaisePropertyChanged("maxThresholdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long sensorId {
            get {
                return this.sensorIdField;
            }
            set {
                this.sensorIdField = value;
                this.RaisePropertyChanged("sensorId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int sensorChannelNum {
            get {
                return this.sensorChannelNumField;
            }
            set {
                this.sensorChannelNumField = value;
                this.RaisePropertyChanged("sensorChannelNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int priority {
            get {
                return this.priorityField;
            }
            set {
                this.priorityField = value;
                this.RaisePropertyChanged("priority");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(noteTaker))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(sensorChannel))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(camera))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://web.syndication.ems.com/")]
    public abstract partial class aCaptureData : aDescription {
        
        private string captureDataTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string captureDataType {
            get {
                return this.captureDataTypeField;
            }
            set {
                this.captureDataTypeField = value;
                this.RaisePropertyChanged("captureDataType");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://web.syndication.ems.com/")]
    public partial class noteTaker : aCaptureData {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://web.syndication.ems.com/")]
    public partial class sensorChannel : aCaptureData {
        
        private int channelNumField;
        
        private string sensorMetricTypeNameField;
        
        private string sensorTypeNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int channelNum {
            get {
                return this.channelNumField;
            }
            set {
                this.channelNumField = value;
                this.RaisePropertyChanged("channelNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string sensorMetricTypeName {
            get {
                return this.sensorMetricTypeNameField;
            }
            set {
                this.sensorMetricTypeNameField = value;
                this.RaisePropertyChanged("sensorMetricTypeName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string sensorTypeName {
            get {
                return this.sensorTypeNameField;
            }
            set {
                this.sensorTypeNameField = value;
                this.RaisePropertyChanged("sensorTypeName");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://web.syndication.ems.com/")]
    public partial class camera : aCaptureData {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDomains", WrapperNamespace="http://web.syndication.ems.com/", IsWrapped=true)]
    public partial class getDomainsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://web.syndication.ems.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GreenLifeLine_NonBlend.EmsSyndicator.user a_user;
        
        public getDomainsRequest() {
        }
        
        public getDomainsRequest(GreenLifeLine_NonBlend.EmsSyndicator.user a_user) {
            this.a_user = a_user;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDomainsResponse", WrapperNamespace="http://web.syndication.ems.com/", IsWrapped=true)]
    public partial class getDomainsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://web.syndication.ems.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public domain[] @return;
        
        public getDomainsResponse() {
        }
        
        public getDomainsResponse(domain[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="login", WrapperNamespace="http://web.syndication.ems.com/", IsWrapped=true)]
    public partial class loginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://web.syndication.ems.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string a_name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://web.syndication.ems.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string a_password;
        
        public loginRequest() {
        }
        
        public loginRequest(string a_name, string a_password) {
            this.a_name = a_name;
            this.a_password = a_password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="loginResponse", WrapperNamespace="http://web.syndication.ems.com/", IsWrapped=true)]
    public partial class loginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://web.syndication.ems.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GreenLifeLine_NonBlend.EmsSyndicator.user @return;
        
        public loginResponse() {
        }
        
        public loginResponse(GreenLifeLine_NonBlend.EmsSyndicator.user @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getEnvironments", WrapperNamespace="http://web.syndication.ems.com/", IsWrapped=true)]
    public partial class getEnvironmentsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://web.syndication.ems.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GreenLifeLine_NonBlend.EmsSyndicator.domain a_domain;
        
        public getEnvironmentsRequest() {
        }
        
        public getEnvironmentsRequest(GreenLifeLine_NonBlend.EmsSyndicator.domain a_domain) {
            this.a_domain = a_domain;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getEnvironmentsResponse", WrapperNamespace="http://web.syndication.ems.com/", IsWrapped=true)]
    public partial class getEnvironmentsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://web.syndication.ems.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public environment[] @return;
        
        public getEnvironmentsResponse() {
        }
        
        public getEnvironmentsResponse(environment[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="notes", WrapperNamespace="http://web.syndication.ems.com/", IsWrapped=true)]
    public partial class notesRequest {
        
        public notesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="notesResponse", WrapperNamespace="http://web.syndication.ems.com/", IsWrapped=true)]
    public partial class notesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://web.syndication.ems.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GreenLifeLine_NonBlend.EmsSyndicator.note @return;
        
        public notesResponse() {
        }
        
        public notesResponse(GreenLifeLine_NonBlend.EmsSyndicator.note @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="helloWorld", WrapperNamespace="http://web.syndication.ems.com/", IsWrapped=true)]
    public partial class helloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://web.syndication.ems.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string a_name;
        
        public helloWorldRequest() {
        }
        
        public helloWorldRequest(string a_name) {
            this.a_name = a_name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="helloWorldResponse", WrapperNamespace="http://web.syndication.ems.com/", IsWrapped=true)]
    public partial class helloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://web.syndication.ems.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public helloWorldResponse() {
        }
        
        public helloWorldResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDataCapturers", WrapperNamespace="http://web.syndication.ems.com/", IsWrapped=true)]
    public partial class getDataCapturersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://web.syndication.ems.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GreenLifeLine_NonBlend.EmsSyndicator.environment a_environment;
        
        public getDataCapturersRequest() {
        }
        
        public getDataCapturersRequest(GreenLifeLine_NonBlend.EmsSyndicator.environment a_environment) {
            this.a_environment = a_environment;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDataCapturersResponse", WrapperNamespace="http://web.syndication.ems.com/", IsWrapped=true)]
    public partial class getDataCapturersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://web.syndication.ems.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public aCaptureData[] @return;
        
        public getDataCapturersResponse() {
        }
        
        public getDataCapturersResponse(aCaptureData[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCurrentData", WrapperNamespace="http://web.syndication.ems.com/", IsWrapped=true)]
    public partial class getCurrentDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://web.syndication.ems.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GreenLifeLine_NonBlend.EmsSyndicator.aCaptureData a_iCaptureData;
        
        public getCurrentDataRequest() {
        }
        
        public getCurrentDataRequest(GreenLifeLine_NonBlend.EmsSyndicator.aCaptureData a_iCaptureData) {
            this.a_iCaptureData = a_iCaptureData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCurrentDataResponse", WrapperNamespace="http://web.syndication.ems.com/", IsWrapped=true)]
    public partial class getCurrentDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://web.syndication.ems.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GreenLifeLine_NonBlend.EmsSyndicator.aData @return;
        
        public getCurrentDataResponse() {
        }
        
        public getCurrentDataResponse(GreenLifeLine_NonBlend.EmsSyndicator.aData @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDataCaptureData", WrapperNamespace="http://web.syndication.ems.com/", IsWrapped=true)]
    public partial class getDataCaptureDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://web.syndication.ems.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GreenLifeLine_NonBlend.EmsSyndicator.aCaptureData a_iCaptureData;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://web.syndication.ems.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long a_startTimestamp;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://web.syndication.ems.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long a_stopTimestamp;
        
        public getDataCaptureDataRequest() {
        }
        
        public getDataCaptureDataRequest(GreenLifeLine_NonBlend.EmsSyndicator.aCaptureData a_iCaptureData, long a_startTimestamp, long a_stopTimestamp) {
            this.a_iCaptureData = a_iCaptureData;
            this.a_startTimestamp = a_startTimestamp;
            this.a_stopTimestamp = a_stopTimestamp;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDataCaptureDataResponse", WrapperNamespace="http://web.syndication.ems.com/", IsWrapped=true)]
    public partial class getDataCaptureDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://web.syndication.ems.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public aData[] @return;
        
        public getDataCaptureDataResponse() {
        }
        
        public getDataCaptureDataResponse(aData[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllSensorRanges", WrapperNamespace="http://web.syndication.ems.com/", IsWrapped=true)]
    public partial class getAllSensorRangesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://web.syndication.ems.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GreenLifeLine_NonBlend.EmsSyndicator.aCaptureData a_iCaptureData;
        
        public getAllSensorRangesRequest() {
        }
        
        public getAllSensorRangesRequest(GreenLifeLine_NonBlend.EmsSyndicator.aCaptureData a_iCaptureData) {
            this.a_iCaptureData = a_iCaptureData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllSensorRangesResponse", WrapperNamespace="http://web.syndication.ems.com/", IsWrapped=true)]
    public partial class getAllSensorRangesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://web.syndication.ems.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public sensorRange[] @return;
        
        public getAllSensorRangesResponse() {
        }
        
        public getAllSensorRangesResponse(sensorRange[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCurrentSensorRangesForEnvironment", WrapperNamespace="http://web.syndication.ems.com/", IsWrapped=true)]
    public partial class getCurrentSensorRangesForEnvironmentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://web.syndication.ems.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long a_envID;
        
        public getCurrentSensorRangesForEnvironmentRequest() {
        }
        
        public getCurrentSensorRangesForEnvironmentRequest(long a_envID) {
            this.a_envID = a_envID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCurrentSensorRangesForEnvironmentResponse", WrapperNamespace="http://web.syndication.ems.com/", IsWrapped=true)]
    public partial class getCurrentSensorRangesForEnvironmentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://web.syndication.ems.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public sensorRange[] @return;
        
        public getCurrentSensorRangesForEnvironmentResponse() {
        }
        
        public getCurrentSensorRangesForEnvironmentResponse(sensorRange[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCurrentSensorRanges", WrapperNamespace="http://web.syndication.ems.com/", IsWrapped=true)]
    public partial class getCurrentSensorRangesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://web.syndication.ems.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GreenLifeLine_NonBlend.EmsSyndicator.aDescription a_iCurrentSensorRanges;
        
        public getCurrentSensorRangesRequest() {
        }
        
        public getCurrentSensorRangesRequest(GreenLifeLine_NonBlend.EmsSyndicator.aDescription a_iCurrentSensorRanges) {
            this.a_iCurrentSensorRanges = a_iCurrentSensorRanges;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCurrentSensorRangesResponse", WrapperNamespace="http://web.syndication.ems.com/", IsWrapped=true)]
    public partial class getCurrentSensorRangesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://web.syndication.ems.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public sensorRange[] @return;
        
        public getCurrentSensorRangesResponse() {
        }
        
        public getCurrentSensorRangesResponse(sensorRange[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="snapShots", WrapperNamespace="http://web.syndication.ems.com/", IsWrapped=true)]
    public partial class snapShotsRequest {
        
        public snapShotsRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="snapShotsResponse", WrapperNamespace="http://web.syndication.ems.com/", IsWrapped=true)]
    public partial class snapShotsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://web.syndication.ems.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GreenLifeLine_NonBlend.EmsSyndicator.snapshot @return;
        
        public snapShotsResponse() {
        }
        
        public snapShotsResponse(GreenLifeLine_NonBlend.EmsSyndicator.snapshot @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="measurements", WrapperNamespace="http://web.syndication.ems.com/", IsWrapped=true)]
    public partial class measurementsRequest {
        
        public measurementsRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="measurementsResponse", WrapperNamespace="http://web.syndication.ems.com/", IsWrapped=true)]
    public partial class measurementsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://web.syndication.ems.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GreenLifeLine_NonBlend.EmsSyndicator.measurement @return;
        
        public measurementsResponse() {
        }
        
        public measurementsResponse(GreenLifeLine_NonBlend.EmsSyndicator.measurement @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cameras", WrapperNamespace="http://web.syndication.ems.com/", IsWrapped=true)]
    public partial class camerasRequest {
        
        public camerasRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="camerasResponse", WrapperNamespace="http://web.syndication.ems.com/", IsWrapped=true)]
    public partial class camerasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://web.syndication.ems.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GreenLifeLine_NonBlend.EmsSyndicator.camera @return;
        
        public camerasResponse() {
        }
        
        public camerasResponse(GreenLifeLine_NonBlend.EmsSyndicator.camera @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="noteTakers", WrapperNamespace="http://web.syndication.ems.com/", IsWrapped=true)]
    public partial class noteTakersRequest {
        
        public noteTakersRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="noteTakersResponse", WrapperNamespace="http://web.syndication.ems.com/", IsWrapped=true)]
    public partial class noteTakersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://web.syndication.ems.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GreenLifeLine_NonBlend.EmsSyndicator.noteTaker @return;
        
        public noteTakersResponse() {
        }
        
        public noteTakersResponse(GreenLifeLine_NonBlend.EmsSyndicator.noteTaker @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sensorChannels", WrapperNamespace="http://web.syndication.ems.com/", IsWrapped=true)]
    public partial class sensorChannelsRequest {
        
        public sensorChannelsRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sensorChannelsResponse", WrapperNamespace="http://web.syndication.ems.com/", IsWrapped=true)]
    public partial class sensorChannelsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://web.syndication.ems.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GreenLifeLine_NonBlend.EmsSyndicator.sensorChannel @return;
        
        public sensorChannelsResponse() {
        }
        
        public sensorChannelsResponse(GreenLifeLine_NonBlend.EmsSyndicator.sensorChannel @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface EmsSyndicatorChannel : GreenLifeLine_NonBlend.EmsSyndicator.EmsSyndicator, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class EmsSyndicatorClient : System.ServiceModel.ClientBase<GreenLifeLine_NonBlend.EmsSyndicator.EmsSyndicator>, GreenLifeLine_NonBlend.EmsSyndicator.EmsSyndicator {
        
        public EmsSyndicatorClient() {
        }
        
        public EmsSyndicatorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmsSyndicatorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmsSyndicatorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmsSyndicatorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GreenLifeLine_NonBlend.EmsSyndicator.getDomainsResponse GreenLifeLine_NonBlend.EmsSyndicator.EmsSyndicator.getDomains(GreenLifeLine_NonBlend.EmsSyndicator.getDomainsRequest request) {
            return base.Channel.getDomains(request);
        }
        
        public domain[] getDomains(GreenLifeLine_NonBlend.EmsSyndicator.user a_user) {
            GreenLifeLine_NonBlend.EmsSyndicator.getDomainsRequest inValue = new GreenLifeLine_NonBlend.EmsSyndicator.getDomainsRequest();
            inValue.a_user = a_user;
            GreenLifeLine_NonBlend.EmsSyndicator.getDomainsResponse retVal = ((GreenLifeLine_NonBlend.EmsSyndicator.EmsSyndicator)(this)).getDomains(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GreenLifeLine_NonBlend.EmsSyndicator.loginResponse GreenLifeLine_NonBlend.EmsSyndicator.EmsSyndicator.login(GreenLifeLine_NonBlend.EmsSyndicator.loginRequest request) {
            return base.Channel.login(request);
        }
        
        public GreenLifeLine_NonBlend.EmsSyndicator.user login(string a_name, string a_password) {
            GreenLifeLine_NonBlend.EmsSyndicator.loginRequest inValue = new GreenLifeLine_NonBlend.EmsSyndicator.loginRequest();
            inValue.a_name = a_name;
            inValue.a_password = a_password;
            GreenLifeLine_NonBlend.EmsSyndicator.loginResponse retVal = ((GreenLifeLine_NonBlend.EmsSyndicator.EmsSyndicator)(this)).login(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GreenLifeLine_NonBlend.EmsSyndicator.getEnvironmentsResponse GreenLifeLine_NonBlend.EmsSyndicator.EmsSyndicator.getEnvironments(GreenLifeLine_NonBlend.EmsSyndicator.getEnvironmentsRequest request) {
            return base.Channel.getEnvironments(request);
        }
        
        public environment[] getEnvironments(GreenLifeLine_NonBlend.EmsSyndicator.domain a_domain) {
            GreenLifeLine_NonBlend.EmsSyndicator.getEnvironmentsRequest inValue = new GreenLifeLine_NonBlend.EmsSyndicator.getEnvironmentsRequest();
            inValue.a_domain = a_domain;
            GreenLifeLine_NonBlend.EmsSyndicator.getEnvironmentsResponse retVal = ((GreenLifeLine_NonBlend.EmsSyndicator.EmsSyndicator)(this)).getEnvironments(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GreenLifeLine_NonBlend.EmsSyndicator.notesResponse GreenLifeLine_NonBlend.EmsSyndicator.EmsSyndicator.notes(GreenLifeLine_NonBlend.EmsSyndicator.notesRequest request) {
            return base.Channel.notes(request);
        }
        
        public GreenLifeLine_NonBlend.EmsSyndicator.note notes() {
            GreenLifeLine_NonBlend.EmsSyndicator.notesRequest inValue = new GreenLifeLine_NonBlend.EmsSyndicator.notesRequest();
            GreenLifeLine_NonBlend.EmsSyndicator.notesResponse retVal = ((GreenLifeLine_NonBlend.EmsSyndicator.EmsSyndicator)(this)).notes(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GreenLifeLine_NonBlend.EmsSyndicator.helloWorldResponse GreenLifeLine_NonBlend.EmsSyndicator.EmsSyndicator.helloWorld(GreenLifeLine_NonBlend.EmsSyndicator.helloWorldRequest request) {
            return base.Channel.helloWorld(request);
        }
        
        public string helloWorld(string a_name) {
            GreenLifeLine_NonBlend.EmsSyndicator.helloWorldRequest inValue = new GreenLifeLine_NonBlend.EmsSyndicator.helloWorldRequest();
            inValue.a_name = a_name;
            GreenLifeLine_NonBlend.EmsSyndicator.helloWorldResponse retVal = ((GreenLifeLine_NonBlend.EmsSyndicator.EmsSyndicator)(this)).helloWorld(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GreenLifeLine_NonBlend.EmsSyndicator.getDataCapturersResponse GreenLifeLine_NonBlend.EmsSyndicator.EmsSyndicator.getDataCapturers(GreenLifeLine_NonBlend.EmsSyndicator.getDataCapturersRequest request) {
            return base.Channel.getDataCapturers(request);
        }
        
        public aCaptureData[] getDataCapturers(GreenLifeLine_NonBlend.EmsSyndicator.environment a_environment) {
            GreenLifeLine_NonBlend.EmsSyndicator.getDataCapturersRequest inValue = new GreenLifeLine_NonBlend.EmsSyndicator.getDataCapturersRequest();
            inValue.a_environment = a_environment;
            GreenLifeLine_NonBlend.EmsSyndicator.getDataCapturersResponse retVal = ((GreenLifeLine_NonBlend.EmsSyndicator.EmsSyndicator)(this)).getDataCapturers(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GreenLifeLine_NonBlend.EmsSyndicator.getCurrentDataResponse GreenLifeLine_NonBlend.EmsSyndicator.EmsSyndicator.getCurrentData(GreenLifeLine_NonBlend.EmsSyndicator.getCurrentDataRequest request) {
            return base.Channel.getCurrentData(request);
        }
        
        public GreenLifeLine_NonBlend.EmsSyndicator.aData getCurrentData(GreenLifeLine_NonBlend.EmsSyndicator.aCaptureData a_iCaptureData) {
            GreenLifeLine_NonBlend.EmsSyndicator.getCurrentDataRequest inValue = new GreenLifeLine_NonBlend.EmsSyndicator.getCurrentDataRequest();
            inValue.a_iCaptureData = a_iCaptureData;
            GreenLifeLine_NonBlend.EmsSyndicator.getCurrentDataResponse retVal = ((GreenLifeLine_NonBlend.EmsSyndicator.EmsSyndicator)(this)).getCurrentData(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GreenLifeLine_NonBlend.EmsSyndicator.getDataCaptureDataResponse GreenLifeLine_NonBlend.EmsSyndicator.EmsSyndicator.getDataCaptureData(GreenLifeLine_NonBlend.EmsSyndicator.getDataCaptureDataRequest request) {
            return base.Channel.getDataCaptureData(request);
        }
        
        public aData[] getDataCaptureData(GreenLifeLine_NonBlend.EmsSyndicator.aCaptureData a_iCaptureData, long a_startTimestamp, long a_stopTimestamp) {
            GreenLifeLine_NonBlend.EmsSyndicator.getDataCaptureDataRequest inValue = new GreenLifeLine_NonBlend.EmsSyndicator.getDataCaptureDataRequest();
            inValue.a_iCaptureData = a_iCaptureData;
            inValue.a_startTimestamp = a_startTimestamp;
            inValue.a_stopTimestamp = a_stopTimestamp;
            GreenLifeLine_NonBlend.EmsSyndicator.getDataCaptureDataResponse retVal = ((GreenLifeLine_NonBlend.EmsSyndicator.EmsSyndicator)(this)).getDataCaptureData(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GreenLifeLine_NonBlend.EmsSyndicator.getAllSensorRangesResponse GreenLifeLine_NonBlend.EmsSyndicator.EmsSyndicator.getAllSensorRanges(GreenLifeLine_NonBlend.EmsSyndicator.getAllSensorRangesRequest request) {
            return base.Channel.getAllSensorRanges(request);
        }
        
        public sensorRange[] getAllSensorRanges(GreenLifeLine_NonBlend.EmsSyndicator.aCaptureData a_iCaptureData) {
            GreenLifeLine_NonBlend.EmsSyndicator.getAllSensorRangesRequest inValue = new GreenLifeLine_NonBlend.EmsSyndicator.getAllSensorRangesRequest();
            inValue.a_iCaptureData = a_iCaptureData;
            GreenLifeLine_NonBlend.EmsSyndicator.getAllSensorRangesResponse retVal = ((GreenLifeLine_NonBlend.EmsSyndicator.EmsSyndicator)(this)).getAllSensorRanges(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GreenLifeLine_NonBlend.EmsSyndicator.getCurrentSensorRangesForEnvironmentResponse GreenLifeLine_NonBlend.EmsSyndicator.EmsSyndicator.getCurrentSensorRangesForEnvironment(GreenLifeLine_NonBlend.EmsSyndicator.getCurrentSensorRangesForEnvironmentRequest request) {
            return base.Channel.getCurrentSensorRangesForEnvironment(request);
        }
        
        public sensorRange[] getCurrentSensorRangesForEnvironment(long a_envID) {
            GreenLifeLine_NonBlend.EmsSyndicator.getCurrentSensorRangesForEnvironmentRequest inValue = new GreenLifeLine_NonBlend.EmsSyndicator.getCurrentSensorRangesForEnvironmentRequest();
            inValue.a_envID = a_envID;
            GreenLifeLine_NonBlend.EmsSyndicator.getCurrentSensorRangesForEnvironmentResponse retVal = ((GreenLifeLine_NonBlend.EmsSyndicator.EmsSyndicator)(this)).getCurrentSensorRangesForEnvironment(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GreenLifeLine_NonBlend.EmsSyndicator.getCurrentSensorRangesResponse GreenLifeLine_NonBlend.EmsSyndicator.EmsSyndicator.getCurrentSensorRanges(GreenLifeLine_NonBlend.EmsSyndicator.getCurrentSensorRangesRequest request) {
            return base.Channel.getCurrentSensorRanges(request);
        }
        
        public sensorRange[] getCurrentSensorRanges(GreenLifeLine_NonBlend.EmsSyndicator.aDescription a_iCurrentSensorRanges) {
            GreenLifeLine_NonBlend.EmsSyndicator.getCurrentSensorRangesRequest inValue = new GreenLifeLine_NonBlend.EmsSyndicator.getCurrentSensorRangesRequest();
            inValue.a_iCurrentSensorRanges = a_iCurrentSensorRanges;
            GreenLifeLine_NonBlend.EmsSyndicator.getCurrentSensorRangesResponse retVal = ((GreenLifeLine_NonBlend.EmsSyndicator.EmsSyndicator)(this)).getCurrentSensorRanges(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GreenLifeLine_NonBlend.EmsSyndicator.snapShotsResponse GreenLifeLine_NonBlend.EmsSyndicator.EmsSyndicator.snapShots(GreenLifeLine_NonBlend.EmsSyndicator.snapShotsRequest request) {
            return base.Channel.snapShots(request);
        }
        
        public GreenLifeLine_NonBlend.EmsSyndicator.snapshot snapShots() {
            GreenLifeLine_NonBlend.EmsSyndicator.snapShotsRequest inValue = new GreenLifeLine_NonBlend.EmsSyndicator.snapShotsRequest();
            GreenLifeLine_NonBlend.EmsSyndicator.snapShotsResponse retVal = ((GreenLifeLine_NonBlend.EmsSyndicator.EmsSyndicator)(this)).snapShots(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GreenLifeLine_NonBlend.EmsSyndicator.measurementsResponse GreenLifeLine_NonBlend.EmsSyndicator.EmsSyndicator.measurements(GreenLifeLine_NonBlend.EmsSyndicator.measurementsRequest request) {
            return base.Channel.measurements(request);
        }
        
        public GreenLifeLine_NonBlend.EmsSyndicator.measurement measurements() {
            GreenLifeLine_NonBlend.EmsSyndicator.measurementsRequest inValue = new GreenLifeLine_NonBlend.EmsSyndicator.measurementsRequest();
            GreenLifeLine_NonBlend.EmsSyndicator.measurementsResponse retVal = ((GreenLifeLine_NonBlend.EmsSyndicator.EmsSyndicator)(this)).measurements(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GreenLifeLine_NonBlend.EmsSyndicator.camerasResponse GreenLifeLine_NonBlend.EmsSyndicator.EmsSyndicator.cameras(GreenLifeLine_NonBlend.EmsSyndicator.camerasRequest request) {
            return base.Channel.cameras(request);
        }
        
        public GreenLifeLine_NonBlend.EmsSyndicator.camera cameras() {
            GreenLifeLine_NonBlend.EmsSyndicator.camerasRequest inValue = new GreenLifeLine_NonBlend.EmsSyndicator.camerasRequest();
            GreenLifeLine_NonBlend.EmsSyndicator.camerasResponse retVal = ((GreenLifeLine_NonBlend.EmsSyndicator.EmsSyndicator)(this)).cameras(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GreenLifeLine_NonBlend.EmsSyndicator.noteTakersResponse GreenLifeLine_NonBlend.EmsSyndicator.EmsSyndicator.noteTakers(GreenLifeLine_NonBlend.EmsSyndicator.noteTakersRequest request) {
            return base.Channel.noteTakers(request);
        }
        
        public GreenLifeLine_NonBlend.EmsSyndicator.noteTaker noteTakers() {
            GreenLifeLine_NonBlend.EmsSyndicator.noteTakersRequest inValue = new GreenLifeLine_NonBlend.EmsSyndicator.noteTakersRequest();
            GreenLifeLine_NonBlend.EmsSyndicator.noteTakersResponse retVal = ((GreenLifeLine_NonBlend.EmsSyndicator.EmsSyndicator)(this)).noteTakers(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GreenLifeLine_NonBlend.EmsSyndicator.sensorChannelsResponse GreenLifeLine_NonBlend.EmsSyndicator.EmsSyndicator.sensorChannels(GreenLifeLine_NonBlend.EmsSyndicator.sensorChannelsRequest request) {
            return base.Channel.sensorChannels(request);
        }
        
        public GreenLifeLine_NonBlend.EmsSyndicator.sensorChannel sensorChannels() {
            GreenLifeLine_NonBlend.EmsSyndicator.sensorChannelsRequest inValue = new GreenLifeLine_NonBlend.EmsSyndicator.sensorChannelsRequest();
            GreenLifeLine_NonBlend.EmsSyndicator.sensorChannelsResponse retVal = ((GreenLifeLine_NonBlend.EmsSyndicator.EmsSyndicator)(this)).sensorChannels(inValue);
            return retVal.@return;
        }
    }
}
